project:
  type: website
  output-dir: docs  # This tells GitHub to look here for the live site

website:
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: paper.qmd
      - icon: file-pdf
        text: "CV"
        href: assets/gyourko_cv.pdf

format:
  html:
    theme: cosmo # A clean, academic look similar to your photo
    css: styles.css
    toc: false